# Generated by Django 4.2.3 on 2023-08-02 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_tag_alter_article_options_scope_article_scopes'),
        ('articles', '0004_remove_article_tags_delete_articletag_delete_tag'),
    ]

    operations = [
    ]
