# Generated by Django 4.2.3 on 2023-08-02 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_merge_20230802_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='sections',
        ),
        migrations.DeleteModel(
            name='ArticleSection',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
